-- Cat Food Tracker schema
create table if not exists public.catfoods (
  id bigint generated by default as identity primary key,
  name text not null,
  type text not null check (type in ('wet', 'dry')),
  brand text not null,
  size text,
  description text,
  user_id uuid not null references auth.users(id) on delete cascade
);

alter table public.catfoods enable row level security;

-- Users can only read their own rows
create policy "catfoods_select_own"
on public.catfoods
for select
using (auth.uid() = user_id);

-- Users can only insert rows for themselves
create policy "catfoods_insert_own"
on public.catfoods
for insert
with check (auth.uid() = user_id);

-- Users can only update their own rows
create policy "catfoods_update_own"
on public.catfoods
for update
using (auth.uid() = user_id)
with check (auth.uid() = user_id);

-- Users can only delete their own rows
create policy "catfoods_delete_own"
on public.catfoods
for delete
using (auth.uid() = user_id);
