import { promises as fs } from "fs";
import path from "path";
import { randomUUID } from "crypto";
import { fileURLToPath } from "url";

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const DB_FILE = path.resolve(__dirname, "../data/db.json");

function generateImageUrl(index) {
  const palette =
    index <= 20
      ? ["#ffd7c2", "#ff9d72", "SEAFOOD BOWL"]
      : index <= 60
        ? ["#fff0c2", "#d8a12f", "CRUNCH BAG"]
        : index <= 85
          ? ["#d8f7df", "#57b77c", "CAT TREATS"]
          : ["#dfe5ff", "#6c7ad8", "WELLNESS CARE"];
  const [surface, accent, label] = palette;
  const svg = `
    <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 640 420">
      <rect width="640" height="420" fill="#fffaf0"/>
      <rect x="22" y="22" width="596" height="376" rx="28" fill="${surface}" stroke="${accent}" stroke-width="6"/>
      <rect x="52" y="52" width="170" height="44" rx="22" fill="${accent}"/>
      <text x="137" y="80" text-anchor="middle" font-family="Arial, Helvetica, sans-serif" font-size="18" font-weight="700" fill="#ffffff">${label}</text>
      <circle cx="490" cy="132" r="74" fill="${accent}" opacity="0.16"/>
      <path d="M438 132c0-46 32-76 72-76 40 0 72 30 72 76 0 61-74 112-74 112s-70-45-70-112z" fill="${accent}" opacity="0.88"/>
      <text x="118" y="220" font-family="Arial, Helvetica, sans-serif" font-size="38" font-weight="800" fill="#2d1b2e">Cat Food</text>
      <text x="118" y="262" font-family="Arial, Helvetica, sans-serif" font-size="24" font-weight="700" fill="#5b4666">shop seed artwork</text>
      <rect x="92" y="296" width="210" height="60" rx="24" fill="${accent}" opacity="0.92"/>
      <text x="197" y="334" text-anchor="middle" font-family="Arial, Helvetica, sans-serif" font-size="26" font-weight="800" fill="#ffffff">cat approved</text>
    </svg>
  `;
  return `data:image/svg+xml;charset=UTF-8,${encodeURIComponent(svg)}`;
}

const seedProducts = [
  {
    title: "Fancy Feast Gourmet Chicken",
    category: "wet",
    brand: "Purina Fancy Feast",
    size: "3 oz",
    description: "Delicious gourmet meal with tender chicken and savory juices. Perfect for picky eaters! Premium ingredients with real chicken.",
    imageUrl: generateImageUrl(1),
    price: 4.99,
    rating: 4.8,
    stock: 150,
  },
  {
    title: "Sheba Perfect Portions Beef",
    category: "wet",
    brand: "Sheba",
    size: "2.6 oz",
    description: "Premium wet food in perfect portions for a complete meal. Rich pâté texture with real beef.",
    imageUrl: generateImageUrl(2),
    price: 5.99,
    rating: 4.7,
    stock: 120,
  },
  {
    title: "Fancy Feast Seafood",
    category: "wet",
    brand: "Purina Fancy Feast",
    size: "3 oz",
    description: "Ocean-inspired flavors with salmon and shrimp. High-quality seafood meal for discerning cats.",
    imageUrl: generateImageUrl(3),
    price: 4.99,
    rating: 4.9,
    stock: 130,
  },
  {
    title: "Sheba Pâté Tuna",
    category: "wet",
    brand: "Sheba",
    size: "2.6 oz",
    description: "Smooth tuna pâté in convenient portions. Nutritionally complete and balanced meal.",
    imageUrl: generateImageUrl(4),
    price: 5.99,
    rating: 4.8,
    stock: 100,
  },
  {
    title: "Purina Pro Plan Chicken Wet",
    category: "wet",
    brand: "Purina Pro Plan",
    size: "5.5 oz",
    description: "Advanced nutrition with probiotics for digestive health. Supports healthy digestion. Veterinary recommended.",
    imageUrl: generateImageUrl(5),
    price: 6.99,
    rating: 4.8,
    stock: 110,
  },
  {
    title: "Fancy Feast Turkey & Gravy",
    category: "wet",
    brand: "Purina Fancy Feast",
    size: "3 oz",
    description: "Tender turkey pieces in rich gravy. Cats love this classic flavor favorite.",
    imageUrl: generateImageUrl(6),
    price: 4.99,
    rating: 4.7,
    stock: 125,
  },
  {
    title: "Friskies Classic Beef",
    category: "wet",
    brand: "Friskies",
    size: "5.5 oz",
    description: "Savory beef pâté with real beef and added vitamins & minerals. Budget-friendly nutrition.",
    imageUrl: generateImageUrl(7),
    price: 2.49,
    rating: 4.3,
    stock: 180,
  },
  {
    title: "9Lives Chicken & Liver",
    category: "wet",
    brand: "9Lives",
    size: "5.5 oz",
    description: "Savory chicken and liver combination. Affordable and nutritious meal.",
    imageUrl: generateImageUrl(8),
    price: 2.99,
    rating: 4.2,
    stock: 160,
  },
  {
    title: "Fancy Feast Salmon Feast",
    category: "wet",
    brand: "Purina Fancy Feast",
    size: "3 oz",
    description: "Premium salmon with essential omega-3 fatty acids. Supports healthy skin and coat.",
    imageUrl: generateImageUrl(9),
    price: 5.49,
    rating: 4.9,
    stock: 115,
  },
  {
    title: "Iams Perfect Portions Turkey",
    category: "wet",
    brand: "Iams",
    size: "2.6 oz",
    description: "Portion-controlled meals with real turkey. Easy to serve and minimize waste.",
    imageUrl: generateImageUrl(10),
    price: 4.49,
    rating: 4.5,
    stock: 105,
  },
  {
    title: "Wellness CORE Salmon",
    category: "wet",
    brand: "Wellness",
    size: "3 oz",
    description: "Grain-free formula with wild salmon. Premium natural ingredients for optimal nutrition.",
    imageUrl: generateImageUrl(11),
    price: 6.99,
    rating: 4.9,
    stock: 95,
  },
  {
    title: "Blue Buffalo Chicken Wet",
    category: "wet",
    brand: "Blue Buffalo",
    size: "3 oz",
    description: "Natural ingredients with chicken and sweet potato. No by-products or fillers.",
    imageUrl: generateImageUrl(12),
    price: 6.49,
    rating: 4.8,
    stock: 100,
  },
  {
    title: "Hill's Science Diet Chicken",
    category: "wet",
    brand: "Hill's",
    size: "5.5 oz",
    description: "Scientifically formulated with chicken. Trusted by veterinarians worldwide.",
    imageUrl: generateImageUrl(13),
    price: 7.99,
    rating: 4.8,
    stock: 90,
  },
  {
    title: "Fancy Feast Creamy Delights",
    category: "wet",
    brand: "Purina Fancy Feast",
    size: "3 oz",
    description: "Creamy, indulgent wet food with real chicken. For cats who love luxury.",
    imageUrl: generateImageUrl(14),
    price: 5.49,
    rating: 4.6,
    stock: 130,
  },
  {
    title: "Meow Mix Tender Centers",
    category: "wet",
    brand: "Meow Mix",
    size: "2.75 oz",
    description: "Soft centers surrounded by crunchy coating. Double texture cats crave.",
    imageUrl: generateImageUrl(15),
    price: 3.99,
    rating: 4.4,
    stock: 140,
  },
  {
    title: "Fancy Feast Filet Mignon",
    category: "wet",
    brand: "Purina Fancy Feast",
    size: "3 oz",
    description: "Premium filet mignon flavor in savory sauce. Gourmet experience for your cat.",
    imageUrl: generateImageUrl(16),
    price: 5.99,
    rating: 4.9,
    stock: 80,
  },
  {
    title: "Purina ONE Salmon",
    category: "wet",
    brand: "Purina ONE",
    size: "3 oz",
    description: "Natural salmon meal as first ingredient. Complete nutrition in natural formula.",
    imageUrl: generateImageUrl(17),
    price: 5.99,
    rating: 4.7,
    stock: 85,
  },
  {
    title: "Royal Canin Wet Indoor",
    category: "wet",
    brand: "Royal Canin",
    size: "3 oz",
    description: "Specially formulated for indoor cats. Supports healthy weight and digestive system.",
    imageUrl: generateImageUrl(18),
    price: 6.99,
    rating: 4.8,
    stock: 75,
  },
  {
    title: "Fancy Feast Savory Centers",
    category: "wet",
    brand: "Purina Fancy Feast",
    size: "3 oz",
    description: "Savory centers in delicious sauce. Multiple flavors cats absolutely love.",
    imageUrl: generateImageUrl(19),
    price: 4.99,
    rating: 4.6,
    stock: 120,
  },
  {
    title: "Friskies Seafood",
    category: "wet",
    brand: "Friskies",
    size: "5.5 oz",
    description: "Delicious seafood medley with salmon and shrimp. Great taste at affordable price.",
    imageUrl: generateImageUrl(20),
    price: 2.99,
    rating: 4.3,
    stock: 150,
  },

  {
    title: "Royal Canin Indoor 15lb",
    category: "dry",
    brand: "Royal Canin",
    size: "15 lb",
    description: "Complete nutrition for indoor cats with optimal fiber blend. Vet recommended! Supports digestive health.",
    imageUrl: generateImageUrl(21),
    price: 34.99,
    rating: 4.9,
    stock: 85,
  },
  {
    title: "Iams Proactive Health",
    category: "dry",
    brand: "Iams",
    size: "16 lb",
    description: "Balanced nutrition for adult cats with chicken flavor. 25+ vitamins & minerals for optimal health.",
    imageUrl: generateImageUrl(22),
    price: 24.99,
    rating: 4.5,
    stock: 100,
  },
  {
    title: "Blue Buffalo Wilderness 12lb",
    category: "dry",
    brand: "Blue Buffalo",
    size: "12 lb",
    description: "Grain-free natural cat food with real meat and fish. No by-products or fillers. Premium nutrition.",
    imageUrl: generateImageUrl(23),
    price: 44.99,
    rating: 4.9,
    stock: 70,
  },
  {
    title: "Hill's Science Diet 15.5lb",
    category: "dry",
    brand: "Hill's",
    size: "15.5 lb",
    description: "Scientifically formulated nutrition from veterinary experts. Trusted by vets worldwide.",
    imageUrl: generateImageUrl(24),
    price: 39.99,
    rating: 4.8,
    stock: 80,
  },
  {
    title: "Wellness Core Grain-Free",
    category: "dry",
    brand: "Wellness",
    size: "11 lb",
    description: "High-protein, grain-free formula with natural ingredients. Premium wellness nutrition.",
    imageUrl: generateImageUrl(25),
    price: 42.99,
    rating: 4.9,
    stock: 65,
  },
  {
    title: "Meow Mix Original 14.2lb",
    category: "dry",
    brand: "Meow Mix",
    size: "14.2 lb",
    description: "The world's most famous cat food jingle! Tasty variety for your feline friend.",
    imageUrl: generateImageUrl(26),
    price: 19.99,
    rating: 4.4,
    stock: 110,
  },
  {
    title: "Purina Pro Plan Indoor 16lb",
    category: "dry",
    brand: "Purina Pro Plan",
    size: "16 lb",
    description: "Advanced formula for indoor cats with probiotics. Supports digestive and immune health.",
    imageUrl: generateImageUrl(27),
    price: 29.99,
    rating: 4.7,
    stock: 95,
  },
  {
    title: "Purina ONE Salmon 16lb",
    category: "dry",
    brand: "Purina ONE",
    size: "16 lb",
    description: "Natural salmon meal as first ingredient. Complete nutrition without animal by-products.",
    imageUrl: generateImageUrl(28),
    price: 32.99,
    rating: 4.8,
    stock: 90,
  },
  {
    title: "Fancy Feast Gourmet Dry",
    category: "dry",
    brand: "Purina Fancy Feast",
    size: "12 lb",
    description: "Gourmet dry food with multiple flavors in each bag. Variety cats adore.",
    imageUrl: generateImageUrl(29),
    price: 22.99,
    rating: 4.6,
    stock: 105,
  },
  {
    title: "Royal Canin Digestive Care",
    category: "dry",
    brand: "Royal Canin",
    size: "13 lb",
    description: "Specially formulated for cats with sensitive digestion. Promotes digestive health.",
    imageUrl: generateImageUrl(30),
    price: 36.99,
    rating: 4.8,
    stock: 70,
  },
  {
    title: "Hill's Science Diet Senior",
    category: "dry",
    brand: "Hill's",
    size: "15.5 lb",
    description: "Optimal nutrition for senior cats 7+ years. Supports joint and brain health.",
    imageUrl: generateImageUrl(31),
    price: 38.99,
    rating: 4.7,
    stock: 65,
  },
  {
    title: "Blue Buffalo Salmon 12lb",
    category: "dry",
    brand: "Blue Buffalo",
    size: "12 lb",
    description: "Wild salmon and sweet potato formula. Supports healthy weight and skin.",
    imageUrl: generateImageUrl(32),
    price: 41.99,
    rating: 4.8,
    stock: 75,
  },
  {
    title: "Wellness Core Indoor",
    category: "dry",
    brand: "Wellness",
    size: "12 lb",
    description: "Grain-free indoor cat formula. Maintains healthy weight of indoor cats.",
    imageUrl: generateImageUrl(33),
    price: 39.99,
    rating: 4.9,
    stock: 70,
  },
  {
    title: "Purina Pro Plan Adult",
    category: "dry",
    brand: "Purina Pro Plan",
    size: "18 lb",
    description: "Advanced nutrition for adult cats. Multiple formulas for different needs.",
    imageUrl: generateImageUrl(34),
    price: 26.99,
    rating: 4.6,
    stock: 100,
  },
  {
    title: "Royal Canin Weight Management",
    category: "dry",
    brand: "Royal Canin",
    size: "15 lb",
    description: "Helps manage weight of adult cats. Supports optimal body condition.",
    imageUrl: generateImageUrl(35),
    price: 35.99,
    rating: 4.7,
    stock: 75,
  },
  {
    title: "Taste of the Wild Dry",
    category: "dry",
    brand: "Taste of the Wild",
    size: "14 lb",
    description: "Premium roasted venison and smoked salmon. Grain-free with high protein.",
    imageUrl: generateImageUrl(36),
    price: 39.99,
    rating: 4.8,
    stock: 65,
  },
  {
    title: "Iams Urinary Tract Health",
    category: "dry",
    brand: "Iams",
    size: "16 lb",
    description: "Supports cat urinary tract health. Maintains proper mineral balance.",
    imageUrl: generateImageUrl(37),
    price: 27.99,
    rating: 4.6,
    stock: 85,
  },
  {
    title: "Fancy Feast Dry Salmon",
    category: "dry",
    brand: "Purina Fancy Feast",
    size: "10 lb",
    description: "Gourmet dry food with ocean salmon. Premium taste experience.",
    imageUrl: generateImageUrl(38),
    price: 24.99,
    rating: 4.7,
    stock: 95,
  },
  {
    title: "Blue Buffalo Indoor 12lb",
    category: "dry",
    brand: "Blue Buffalo",
    size: "12 lb",
    description: "Specially formulated for indoor cats. Natural ingredients for indoor wellness.",
    imageUrl: generateImageUrl(39),
    price: 40.99,
    rating: 4.8,
    stock: 70,
  },
  {
    title: "Hill's Perfect Weight",
    category: "dry",
    brand: "Hill's",
    size: "15 lb",
    description: "Helps manage weight while maintaining muscle. Scientifically formulated.",
    imageUrl: generateImageUrl(40),
    price: 37.99,
    rating: 4.7,
    stock: 75,
  },

  {
    title: "Temptations Treats 85g",
    category: "treat",
    brand: "Temptations",
    size: "85g",
    description: "Irresistible cat treats with a crunchy shell and soft center. Cats can't resist! Made with real chicken.",
    imageUrl: generateImageUrl(41),
    price: 3.49,
    rating: 4.8,
    stock: 200,
  },
  {
    title: "Greenies Feline Treats 71g",
    category: "treat",
    brand: "Greenies",
    size: "71g",
    description: "Natural dental treats that clean teeth while your cat chews. Fresh breath guaranteed!",
    imageUrl: generateImageUrl(42),
    price: 4.99,
    rating: 4.6,
    stock: 150,
  },
  {
    title: "Temptations Seafood",
    category: "treat",
    brand: "Temptations",
    size: "85g",
    description: "Delicious seafood-flavored treats with irresistible aroma. Cats go crazy for seafood!",
    imageUrl: generateImageUrl(43),
    price: 3.49,
    rating: 4.7,
    stock: 180,
  },
  {
    title: "Meow Mix Treats Original",
    category: "treat",
    brand: "Meow Mix",
    size: "2.6 oz",
    description: "The iconic Meow Mix flavor in treat form. Multiple flavors in one pouch.",
    imageUrl: generateImageUrl(44),
    price: 2.49,
    rating: 4.4,
    stock: 200,
  },
  {
    title: "Fancy Feast Creamy Treats",
    category: "treat",
    brand: "Purina Fancy Feast",
    size: "3 oz",
    description: "Creamy and delicious treat for special moments. Premium gourmet experience.",
    imageUrl: generateImageUrl(45),
    price: 3.99,
    rating: 4.7,
    stock: 170,
  },
  {
    title: "Greenies Salmon Treats",
    category: "treat",
    brand: "Greenies",
    size: "3 oz",
    description: "Salmon-flavored dental treats. Great for dental health and breath freshness.",
    imageUrl: generateImageUrl(46),
    price: 5.99,
    rating: 4.6,
    stock: 130,
  },
  {
    title: "Temptations Chicken Treats",
    category: "treat",
    brand: "Temptations",
    size: "85g",
    description: "Classic chicken flavor in irresistible treat form. Cats love every bite!",
    imageUrl: generateImageUrl(47),
    price: 3.49,
    rating: 4.8,
    stock: 190,
  },
  {
    title: "Friskies Party Mix",
    category: "treat",
    brand: "Friskies",
    size: "2.1 oz",
    description: "Crunchy and crispy treat variety. Mix of different fun flavors and textures.",
    imageUrl: generateImageUrl(48),
    price: 2.99,
    rating: 4.3,
    stock: 160,
  },
  {
    title: "Iams Kitten Treats",
    category: "treat",
    brand: "Iams",
    size: "2.5 oz",
    description: "Specially formulated for kittens' developing needs. Nutritious and delicious.",
    imageUrl: generateImageUrl(49),
    price: 3.99,
    rating: 4.5,
    stock: 140,
  },
  {
    title: "Wellness Grain-Free Treats",
    category: "treat",
    brand: "Wellness",
    size: "2 oz",
    description: "Natural grain-free treats with chicken. No artificial flavors or colors.",
    imageUrl: generateImageUrl(50),
    price: 4.99,
    rating: 4.7,
    stock: 120,
  },
  {
    title: "Temptations Tuna Treats",
    category: "treat",
    brand: "Temptations",
    size: "85g",
    description: "Tuna-flavored crunchy treats. Irresistible ocean flavor cats adore.",
    imageUrl: generateImageUrl(51),
    price: 3.49,
    rating: 4.8,
    stock: 185,
  },
  {
    title: "Purina ONE Treats Salmon",
    category: "treat",
    brand: "Purina ONE",
    size: "1.3 oz",
    description: "Natural salmon treats from Purina ONE. High protein, no fillers.",
    imageUrl: generateImageUrl(52),
    price: 4.49,
    rating: 4.6,
    stock: 125,
  },
  {
    title: "Blue Buffalo Treats",
    category: "treat",
    brand: "Blue Buffalo",
    size: "2.5 oz",
    description: "Natural ingredient treats with real chicken. No by-products or fillers.",
    imageUrl: generateImageUrl(53),
    price: 5.99,
    rating: 4.8,
    stock: 110,
  },
  {
    title: "Greenies Chicken Treats",
    category: "treat",
    brand: "Greenies",
    size: "3.5 oz",
    description: "Chicken-flavored dental health treats. Cleans teeth while cat enjoys.",
    imageUrl: generateImageUrl(54),
    price: 5.99,
    rating: 4.7,
    stock: 115,
  },
  {
    title: "Hill's Science Diet Treats",
    category: "treat",
    brand: "Hill's",
    size: "2.6 oz",
    description: "Scientifically formulated treats from Hill's. Complete nutrition in small bites.",
    imageUrl: generateImageUrl(55),
    price: 4.99,
    rating: 4.7,
    stock: 130,
  },

  {
    title: "Taurine Supplement 3.35 oz",
    category: "supplement",
    brand: "Vetri-Science",
    size: "3.35 oz",
    description: "Essential amino acid supplement for heart and eye health. Critical for feline wellness. Vet recommended.",
    imageUrl: generateImageUrl(56),
    price: 12.99,
    rating: 4.7,
    stock: 60,
  },
  {
    title: "Fish Oil Omega-3 8oz",
    category: "supplement",
    brand: "Natural Pet",
    size: "8 oz",
    description: "Premium Omega-3 fish oil for coat and joint health. Supports healthy skin & fur. Anti-inflammatory.",
    imageUrl: generateImageUrl(57),
    price: 14.99,
    rating: 4.8,
    stock: 50,
  },
  {
    title: "Probiotic Powder 2.1 oz",
    category: "supplement",
    brand: "PetDigest",
    size: "2.1 oz",
    description: "Daily probiotic powder for gut health. Improves digestion and immune function.",
    imageUrl: generateImageUrl(58),
    price: 16.99,
    rating: 4.7,
    stock: 40,
  },
  {
    title: "L-Lysine Supplement",
    category: "supplement",
    brand: "Vetri-Science",
    size: "3.5 oz",
    description: "Amino acid supplement for immune support. Helps with feline herpesvirus management.",
    imageUrl: generateImageUrl(59),
    price: 13.99,
    rating: 4.6,
    stock: 35,
  },
  {
    title: "Glucosamine Chondroitin",
    category: "supplement",
    brand: "Cosequin",
    size: "120 capsules",
    description: "Joint support for arthritic and aging cats. Promotes cartilage health and mobility.",
    imageUrl: generateImageUrl(60),
    price: 24.99,
    rating: 4.8,
    stock: 30,
  },
  {
    title: "Fish Oil Liquid 4oz",
    category: "supplement",
    brand: "SeaHeat",
    size: "4 oz",
    description: "Liquid fish oil for easy administration. Supports coat and joint health.",
    imageUrl: generateImageUrl(61),
    price: 12.99,
    rating: 4.7,
    stock: 45,
  },
  {
    title: "Cranberry Supplement",
    category: "supplement",
    brand: "NatureVet",
    size: "4 oz",
    description: "Cranberry extract for urinary tract health. Prevents UTI in cats.",
    imageUrl: generateImageUrl(62),
    price: 11.99,
    rating: 4.5,
    stock: 40,
  },
  {
    title: "Digestive Enzyme Powder",
    category: "supplement",
    brand: "Prozyme",
    size: "3 oz",
    description: "Enzyme powder to improve digestion and nutrient absorption. Helps sensitive stomachs.",
    imageUrl: generateImageUrl(63),
    price: 15.99,
    rating: 4.6,
    stock: 35,
  },
  {
    title: "Vitamin B Complex Spray",
    category: "supplement",
    brand: "Liquid Health",
    size: "1 oz",
    description: "B vitamins in spray form for appetite and energy support. Easy application.",
    imageUrl: generateImageUrl(64),
    price: 9.99,
    rating: 4.4,
    stock: 50,
  },
  {
    title: "Joint Supplement Liquid",
    category: "supplement",
    brand: "AnimaCare",
    size: "8 oz",
    description: "Liquid glucosamine and chondroitin for flexible joints. Supports mobility in aging cats.",
    imageUrl: generateImageUrl(65),
    price: 18.99,
    rating: 4.7,
    stock: 30,
  },
  {
    title: "Hairball Control Supplement",
    category: "supplement",
    brand: "Laxatone",
    size: "2.5 oz",
    description: "Helps prevent and resolve hairball issues. Lubricates digestive tract naturally.",
    imageUrl: generateImageUrl(66),
    price: 8.99,
    rating: 4.5,
    stock: 55,
  },
  {
    title: "Probiotic Chews",
    category: "supplement",
    brand: "FortiFlora",
    size: "30 chews",
    description: "Probiotic chewable supplements for digestive health. Includes beneficial microorganisms.",
    imageUrl: generateImageUrl(67),
    price: 22.99,
    rating: 4.8,
    stock: 25,
  },
  {
    title: "CoQ10 Supplement",
    category: "supplement",
    brand: "Petcarevet",
    size: "60 tablets",
    description: "Antioxidant supplement for heart health and energy. Supports aging cats.",
    imageUrl: generateImageUrl(68),
    price: 19.99,
    rating: 4.6,
    stock: 20,
  },
  {
    title: "Omega-3 Fish Oil Capsules",
    category: "supplement",
    brand: "Nordic Naturals",
    size: "90 capsules",
    description: "Premium fish oil in capsule form. Pure EPA and DHA for joint and coat health.",
    imageUrl: generateImageUrl(69),
    price: 21.99,
    rating: 4.9,
    stock: 25,
  },
  {
    title: "Immune Booster Supplement",
    category: "supplement",
    brand: "Immunopet",
    size: "2 oz liquid",
    description: "Immune system support with colostrum and transfer factors. Protects against illness.",
    imageUrl: generateImageUrl(70),
    price: 17.99,
    rating: 4.7,
    stock: 30,
  },
];

async function seed() {
  try {
    await fs.mkdir(path.dirname(DB_FILE), { recursive: true });

    const db = {
      users: [
        {
          id: "demo-seller-1",
          name: "Lucky Cat Supplies",
          email: "seller@example.com",
          passwordHash: "$2a$10$IJQjW.JZ0UezijxHrMhi5umsGJmov9MJvG7dbQtEr1jV4C/hNZXNW",
          role: "seller",
          createdAt: new Date().toISOString(),
          updatedAt: new Date().toISOString(),
        },
      ],
      products: seedProducts.map((product) => ({
        ...product,
        id: randomUUID(),
        seller: "demo-seller-1",
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
      })),
      rescueReports: [
        {
          id: randomUUID(),
          catName: "Marble",
          city: "Brooklyn, NY",
          contactName: "Nina",
          contactInfo: "nina@example.com",
          description: "Friendly tuxedo cat sleeping near a bakery patio. Seems used to people and needs foster placement.",
          status: "needs foster",
          createdAt: new Date().toISOString(),
        },
      ],
      musicianPosts: [
        {
          id: randomUUID(),
          stageName: "DJ Whiskerbeat",
          style: "Lo-fi purr jazz",
          caption: "Tonight's set is dedicated to rescue cats and late-night kibble runs.",
          favoriteTrack: "Moonlight Meow Sonata",
          createdAt: new Date().toISOString(),
        },
      ],
    };

    await fs.writeFile(DB_FILE, JSON.stringify(db, null, 2));
    console.log(`✅ Database seeded with ${db.products.length} products!`);
    console.log(`📊 Breakdown:`);
    console.log(`  🌊 Wet Food: ${seedProducts.filter(p => p.category === "wet").length} products`);
    console.log(`  🥗 Dry Food: ${seedProducts.filter(p => p.category === "dry").length} products`);
    console.log(`  🍖 Treats: ${seedProducts.filter(p => p.category === "treat").length} products`);
    console.log(`  💊 Supplements: ${seedProducts.filter(p => p.category === "supplement").length} products`);
    console.log(`✅ Demo seller: seller@example.com / password123`);
  } catch (err) {
    console.error("✗ Seed failed:", err);
    process.exit(1);
  }
}

seed();
